In [1]:
import pandas as pd

In [3]:
tsf = pd.read_csv('ft_effect_tsf_snps.csv')

In [ ]:
X4_10999638
X4_10998495 
X4_10998766 
X4_10998998 
X4_10999217 
X4_10999229]

X4_10998246	
X4_10998247
X4_10998511	
X4_10998518	
X4_10998605	
X4_10998779	
X4_10998960	
X4_10999396

In [18]:
# First list
highco_bio1 = ["X4_10999638", "X4_10998495", "X4_10998766", "X4_10998998", "X4_10999217", "X4_10999229"]

# Second list
lfmm = ["X4_10998246", "X4_10998247", "X4_10998511", "X4_10998518", "X4_10998605", "X4_10998779", "X4_10998960", "X4_10999396"]

In [19]:
lfmm = tsf[tsf['snp'].isin(lfmm)]

In [20]:
highco_bio1 = tsf[tsf['snp'].isin(highco_bio1)]

In [22]:
highco_bio1

,snp,r_kendall,p_kendall,r_pearson,p_pearson,r_spearman,p_spearman,trait,mean_diff,p_value
4,X4_10998495,0.281649,3.196024e-08,0.227807,0.001441,0.367882,1.414677e-07,FT10,-4.555759,0.440101
5,X4_10998495,0.281649,3.196024e-08,0.227807,0.001441,0.367882,1.414677e-07,FT16,-0.519485,0.673353
12,X4_10998766,0.281649,3.196024e-08,0.227807,0.001441,0.367882,1.414677e-07,FT10,-5.029204,0.437510
13,X4_10998766,0.281649,3.196024e-08,0.227807,0.001441,0.367882,1.414677e-07,FT16,-4.872615,0.713849
18,X4_10998998,0.281649,3.196024e-08,0.227807,0.001441,0.367882,1.414677e-07,FT10,-1.838508,0.353205
19,X4_10998998,0.281649,3.196024e-08,0.227807,0.001441,0.367882,1.414677e-07,FT16,-7.594074,0.053360
20,X4_10999217,0.281649,3.196024e-08,0.227807,0.001441,0.367882,1.414677e-07,FT10,-9.370869,0.481177
21,X4_10999217,0.281649,3.196024e-08,0.227807,0.001441,0.367882,1.414677e-07,FT16,-11.711428,0.597869
22,X4_10999229,0.281649,3.196024e-08,0.227807,0.001441,0.367882,1.414677e-07,FT10,-8.581545,0.418622
23,X4_10999229,0.281649,3.196024e-08,0.227807,0.001441,0.367882,1.414677e-07,FT16,-0.726393,0.984715
26,X4_10999638,0.297093,2.509051e-09,0.216177,0.002532,0.397479,1.042520e-08,FT10,-6.415978,0.330376
27,X4_10999638,0.297093,2.509051e-09,0.216177,0.002532,0.397479,1.042520e-08,FT16,-14.888751,0.070772

In [36]:
pvalues = pd.read_csv('../lfmm_full_last_gen/lfmm_fullresults_all_k/lfmm_bio1_k16_results.csv')

In [35]:
es = pd.read_csv('../lfmm_full_last_gen/lfmm_fullresults_all_k/effect_sizes_simple_full_genome_bio1_k16.csv')

In [40]:
lfmm_results = pd.concat([pvalues, es], axis=1)

In [44]:
lfmm_results['snp_id'] = 'X' + lfmm_results['snp_id']

In [52]:
ft_tsf = lfmm_results[['snp_id', 'bio1']].merge(lfmm, right_on = 'snp', left_on  = 'snp_id')

In [54]:
ft_tsf.columns

Index(['snp_id', 'bio1', 'snp', 'r_kendall', 'p_kendall', 'r_pearson',
       'p_pearson', 'r_spearman', 'p_spearman', 'trait', 'mean_diff',
       'p_value'],
      dtype='object')

In [57]:
ft_tsf = ft_tsf[['snp_id', 'bio1', 'r_kendall', 'p_kendall', 'r_pearson',
       'p_pearson', 'r_spearman', 'p_spearman', 'trait', 'mean_diff',
       'p_value']]

In [60]:
ft_tsf.columns = ['snp_id', 'effect_size_LFMM', 'r_kendall', 'p_kendall', 'r_pearson',
       'p_pearson', 'r_spearman', 'p_spearman', 'chamber_temp', 'mean_diff',
       'p_value']

In [61]:
ft_tsf.to_csv('tsfalleles_flowering_time.csv',index=None)

In [23]:
lfmm[lfmm['mean_diff'] > 0 ]

,snp,r_kendall,p_kendall,r_pearson,p_pearson,r_spearman,p_spearman,trait,mean_diff,p_value
0,X4_10998246,0.161647,1.169181e-03,0.151550,0.035388,0.233385,0.001089,FT10,5.706049,0.002399
1,X4_10998246,0.161647,1.169181e-03,0.151550,0.035388,0.233385,0.001089,FT16,9.785782,0.000149
2,X4_10998247,0.046448,3.489053e-01,-0.081554,0.259528,0.072622,0.315536,FT10,5.924248,0.001177
3,X4_10998247,0.046448,3.489053e-01,-0.081554,0.259528,0.072622,0.315536,FT16,10.276774,0.000051
6,X4_10998511,0.043053,3.892231e-01,-0.002097,0.976908,0.076403,0.290937,FT10,5.019358,0.010653
7,X4_10998511,0.043053,3.892231e-01,-0.002097,0.976908,0.076403,0.290937,FT16,9.060206,0.000816
8,X4_10998518,0.247167,7.263695e-07,0.180321,0.012093,0.335984,0.000002,FT10,5.628811,0.001822
9,X4_10998518,0.247167,7.263695e-07,0.180321,0.012093,0.335984,0.000002,FT16,10.833692,0.000024
14,X4_10998779,0.042344,3.947152e-01,-0.021607,0.765506,0.050712,0.483684,FT10,7.485945,0.000171
15,X4_10998779,0.042344,3.947152e-01,-0.021607,0.765506,0.050712,0.483684,FT16,12.269240,0.000009
16,X4_10998960,0.204400,1.640842e-04,0.195099,0.006548,0.268892,0.000156,FT10,4.635856,0.023373
17,X4_10998960,0.204400,1.640842e-04,0.195099,0.006548,0.268892,0.000156,FT16,8.573411,0.001036

In [24]:
lfmm[lfmm['mean_diff'] < 0 ]

,snp,r_kendall,p_kendall,r_pearson,p_pearson,r_spearman,p_spearman,trait,mean_diff,p_value
10,X4_10998605,-0.076874,0.122629,-0.106841,0.139173,-0.102667,0.155378,FT10,-3.882113,0.005828
11,X4_10998605,-0.076874,0.122629,-0.106841,0.139173,-0.102667,0.155378,FT16,-8.829239,0.000040
24,X4_10999396,0.139547,0.005918,0.133766,0.063652,0.204693,0.004297,FT10,-3.792783,0.004757
25,X4_10999396,0.139547,0.005918,0.133766,0.063652,0.204693,0.004297,FT16,-8.635818,0.000012

In [25]:

snp	r_kendall	p_kendall	r_pearson	p_pearson	r_spearman	p_spearman	trait	mean_diff	p_value
24	X4_10999396	0.139547	0.005918	0.133766	0.063652	0.204693	0.004297	FT10	-3.792783	0.004757
25	X4_10999396	0.139547	0.005918	0.133766	0.063652	0.204693	0.004297	FT16	-8.635818	0.000012

SyntaxError: invalid syntax (1459885714.py, line 1)